<?php

/**
 * @file
 * Contains dram_migrate.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dram_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.dram_migrate':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Migration from MYSQL tables to Drupal core entities') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function dram_migrate() {
  return [
    'dram_migrate' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_uninstall().
 *
 * Removes stale migration configs during uninstall.
 */
function dram_migrate_uninstall() {
  $migrations = [
    'album',
    'category',
    'instrument',
    'label',
    'person',
    'release',
    'track',
    'work',
    'organization',
    'performer',
    'instrument_hierarchy',
    'role',
    'ensemble',
    'file',
    'file_media',
    'file_liner_notes',
    'file_media_liner_notes',
    'file_release_artwork',
    'file_media_release_artwork'
  ];
  foreach ($migrations as $migration) {
    Drupal::configFactory()->getEditable('migrate_plus.migration.' . $migration)->delete();
  }
}
