# Migration metadata
id: file_media_release_artwork
label: file_media_release_artwork
migration_group: "DRAM files and media"

source:
  plugin: file_media_release_artwork
  track_changes: true
  ids: [id]

# Process plugin
process:
  uid:
    plugin: default_value
    default_value: 2
  fid: fid
  mid: mid
  name: title
  field_media_image/target_id:
    plugin: migration_lookup
    migration: file_release_artwork
    source: fid
  field_media_image/alt:
    plugin: default_value
    default_value: "Album artwork"
  field_id_vendor: catalog_number
  field_recording_label:
    plugin: entity_lookup
    entity_type: node
    value_key: title
    source: label_name
  field_primary:
    plugin: default_value
    default_value: 1
  field_media_type:
    source: media_type
    plugin: entity_lookup
    entity_type: taxonomy_term
    bundle_key: vid
    bundle: media_type
    value_key: name
    ignore_case: true

# Destination plugin
destination:
  plugin: entity:media
  default_bundle: release_artwork
  move: false

migration_dependencies: {}
