# Migration metadata
id: ensemble
label: ensemble
description: Migration from MYSQL tables to Drupal core entities

source:
  plugin: ensemble
  track_changes: true
  constants:
    NWR_URL: "http://dramonline.org/ensembles"
  ids:
    id:
      type: integer

# Destination plugin
destination:
  plugin: entity:node

# Process plugin
process:
  type:
    plugin: default_value
    default_value: ensemble
  uid:
    - plugin: default_value
      default_value: 2
  title: name
  field_dram_id: id
  field_legacy_id: legacy_id
  field_active: active
  field_ensemble_type:
    source: type
    plugin: entity_lookup
    entity_type: taxonomy_term
    bundle_key: vid
    bundle: ensemble_type
    value_key: name
    ignore_case: true
  pseudo_link:
    plugin: concat
    source:
      - constants/NWR_URL
      - url_code
    delimiter: "/"
  "field_legacy_url/uri": "@pseudo_link"
  "field_legacy_url/title": url_code

  field_moved: moving

migration_dependencies: {}
