# Migration metadata
id: file_media_liner_notes
label: file_media_liner_notes
migration_group: "DRAM files and media"

source:
  plugin: file_media_liner_notes
  track_changes: true
  constants:
    DESTINATION: "public://notes"
  ids: [id]

# Process plugin
process:
  uid:
    plugin: default_value
    default_value: 2
  fid: fid
  mid: mid
  field_dram_id: release_id
  filename: filename
  filemime:
    plugin: default_value
    default_value: "application/pdf"
  name: title
  field_media_document/target_id:
    plugin: migration_lookup
    migration: file_liner_notes
    source: fid
  field_media_document/display:
    plugin: default_value
    default_value: 1
  field_media_document/description: title
  field_recording_label:
    plugin: entity_lookup
    entity_type: node
    value_key: title
    source: label_name
  field_id_vendor: catalog_number
  field_media_type:
    source: media_type
    plugin: entity_lookup
    entity_type: taxonomy_term
    bundle_key: vid
    bundle: media_type
    value_key: name
    ignore_case: true

  pseudo_destination_path:
    plugin: concat
    source:
      - constants/DESTINATION
      - label_short_name
      - filename
    delimiter: /

# Destination plugin
destination:
  plugin: entity:media
  default_bundle: liner_note
  move: false

migration_dependencies: {}
