# Migration metadata
id: tag
label: tag
description: Migration from MYSQL tables to Drupal core entities

source:
  plugin: tag
  track_changes: true
  ids: id

# Process plugin
process:
  uid:
    - plugin: default_value
      default_value: 2
  name: tag
  field_dram_id/value: id

# Destination plugin
destination:
  plugin: entity:taxonomy_term
  default_bundle: subjects_genre_form

# Nothing needed here, it is a single table without any other relation.
migration_dependencies: {}
